### ISSUE TITLE
Feature request: History 

### ISSUE THREAD

**Issue by jutulen** [nccgroup/Scout2#112]
Would it be possible to add some history functionality to the tool? The way it currently works is that the JSON file with the results are overwritten each time the script is run. 

Could the JSON reports filename be time-stamped and then allow the interface to open previous reports from a list?

A more ambitious idea would be to have a dashboard that shows trends of green/orange/red items over time to show progress towards an all green dashboard. Possibly with some charts?

Does anyone else think this is a good idea?

**Comment by l01cd3v** [comment]
Thanks for the request, here are my answers:

1. Times-stamping reports is definitely doable; I'll most likely add a --timestamp parameter that defaults to the current time in UTC and can be overwritten with whatever users choose. Reports and config files would have the timestamp as a suffix too (e.g. report-<profile_name>-timestamp.html). Does this sound ok?

2. Loading previous reports in a single HTML report would be doable but I'd rather not implement this feature. Once reports are time-stamped, opening two (or more) reports in separate tabs will be comparable and it will help avoiding crazy-sized DOMs that may become irresponsive when multiple runs are in memory for the same DOM.

3. I will not add support for trend because I want to keep Scout2 as a security auditing tool and adding trends/charts does not add value from an auditor's point of view.
