### ISSUE TITLE
Feature Request : List all root account usages 

### ISSUE THREAD

**Issue by HIMANSHU-ELIGIBLE** [nccgroup/Scout2#113]
Hello, 

Currently, if root account password is used in last 90 days, violation shows when the password was used last time. I wanted to discuss the possibility of showing all the activities in last 90 days rather than just latest one. Is it possible ? 

Thanks
Himanshu

**Comment by l01cd3v** [comment]
Hello Himanshu,

I will not add this feature to Scout2 because the tool is not meant to do any sort of parsing/analysis of the activity logs. This warning can easily be set by accessing the credentials report, but access to the activity requires downloading and parsing CloudTrail log files.

I have done this before using different tools. If you already send and aggregate your cloudtrail logs somewhere, you can probably easily query this information there. Otherwise, you can try to do it on your computer assuming you have a decent amount of available disk space & your account does not create an insanely big amount of logs.

You can download all the CloudTrail log files using this python tool from the AWS-recipes repo:
https://github.com/nccgroup/AWS-recipes/blob/master/Python/aws_cloudtrail_get_logs.py

Then write your own python code that does something like:
for each file in logs, open it, transform the JSON string to a python object, iterate through all events and save/print those associated with the root account.
