### ISSUE TITLE
Multiple Account Auditing

### ISSUE THREAD

**Issue by cplvic** [nccgroup/Scout2#126]
I created a cross account role but it seems data is fetched for the account where the user account.
So for example

Account1 - Created role, Read only policy, and User account
Account2 - Created a cross account role, Read only policy and setup a Trust pointing to the user account from Account1.

I ran Scout2.py but I don't see any information from Account2. I was wondering if this has been done before?

**Comment by l01cd3v** [comment]
Scout2 supports role (STS) credentials, but you need to instruct it to use these, it does not automatically identifies/guess roles that may be assumed. It works in a similar fashion than the AWS CLI:

http://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_use_switch-role-cli.html

If you ran Scout2 successfully with Account1, I'm assuming you configured your computer with credentials in Account1 and that the associated user is authorized to assume the role in Account2.

Then the only thing you'd need to do is add the following lines in your ~/.aws/config file:

[profile account2-readonly]
role_arn = arn:aws:iam::Account2AWSAccountID:role/Account2RoleName
source_profile = default

If you specified a profile name for your account1 user's credential, then use this value instead of "default".

I advise you test that you can assume the role with the AWS CLI first:

aws --profile account2-readonly iam list-users

If this works, then you can run Scout2 with the role's credentials:

./Scout2.py --profile account2-readonly

You'll have a new report-account2-readonly.html file ready to be viewed once the tool is done running.

**Comment by Fodoj** [comment]
Just to be clear - there is no unified report for multiple accounts at once, I still need to generate one report per account and see them separetely ?

**Comment by l01cd3v** [comment]
Correct

**Comment by muraliKrishnaBandari** [comment]
Hi, Where can i get the Scout2/py script. Please help me
