### ISSUE TITLE
Documentation for using exceptions file

### ISSUE THREAD

**Issue by abedra** [nccgroup/Scout2#153]
Is there documentation available for what to put into the exceptions files? I see the option available but have not had any luck figuring out what to actually put in it.

**Comment by l01cd3v** [comment]
I have plans to allow management of exceptions via the UI, but I'll try to give you a sample meanwhile.

**Comment by abedra** [comment]
Thanks! All I really need right now is a little documentation around what to add to the exception file to make it ignore things sans ui. If you have a couple of examples that would be much appreciated.

**Comment by l01cd3v** [comment]
Here's a sample file that flags 2 different findings as exceptions:

`{
    "services": {
        "iam": {
            "exceptions": {
                "iam-group-with-inline-policies": [
                    "iam.groups.AGPAIUZCJ2ZNXH2OVMGZS.inline_policies",
                    "foobar"
                ]
            }
        },
        "ec2": {
            "exceptions": {
                "ec2-security-group-opens-SSH-port-to-all": [
                    "ec2.regions.us-east-1.vpcs.vpc-de4977b9.security_groups.sg-fd10b481.rules.ingress.protocols.TCP.ports.22.cidrs.0.CIDR"
                ]
            }
        }
    }
}`

Gist for formatting : https://gist.github.com/l01cd3v/47f52c0179fe641d857f4185b4dc451a

Usage:

`./Scout2.py --local --exceptions exceptions.json`

In order to figure out the values for the finding keys, look at the URL anchor after browsing to a finding that contains exceptions :

#services.ec2.findings.ec2-security-group-opens-MySQL-port-to-all.items 
 >>>
ec2.findings.ec2-security-group-opens-MySQL-port-to-all

For the values of the findings, it's more tricky (hence the need for a UI-based tool) because the path is specified using IDs. I would run Scout2 in debug mode ( --debug ) and manually look for the values in the aws_config(-profile).js file. 

I will add support for regex as well in the future, but right now the full path of each item has to be added. If you need regex support and are willing to put a PR, the file to modify would be AWSScout2/rules/exceptions.py

**Comment by abedra** [comment]
Thanks! This is super helpful. I'm going to start working with it now to see if I need regex support. If I do I'll send a PR.

**Comment by l01cd3v** [comment]
Great, thanks !
