### ISSUE TITLE
No finding if usage is 0

### ISSUE THREAD

**Issue by jjegg** [nccgroup/Scout2#209]
Within the EC2 is there a way to update the rule to also check for usage? For example, I would like to not alert on rule RDP Port open to all, if the security group is not used by an instance.

**Comment by l01cd3v** [comment]
There's no "easy" way to do so right now (i.e. nothing via the CLI / UI), but you can do so by doing the following "hack":

Edit the filer under AWSScout2/rules/data/findings/ec2-security-group-opens-known-port-to-all.json and add the following condition (make sure to add a comma before/after depending where you add it in the list of conditions so that this is still a valid JSON payload):

```
[ "ec2.regions.id.vpcs.id.security_groups.id.", "withoutKey", "used_by" ]
```

Note that this will not only affect the RDP rule but all of the port-specific rules (except for the plaintext protocol ones). If you want to make it just for RDP, you may copy this base rule, add the condition above, and edit the ruleset file such that you source the new file name for the RDP case.

I agree that this feature would be helpful and I'll try to get something to work; however I'd argue that keeping such a security group (or at least this specific grant) because it's not used by an instance is is not a good reason and seems like an incident waiting to happen ;)

**Comment by jjegg** [comment]
Agreed that having the security group still living is bad, however, you could argue that when the security group is attached, the severity level would increase.

**Comment by l01cd3v** [comment]
Yes, I'm thinking that maybe the easiest/best way to go would be to have a new ruleset that has one rule for used SGs in red, and one for unused SGs in yellow. Then you'd enable this feature with something like
```
--ruleset <tbd>
```
I don't think I'd want to make this behavior default to keep the dashboard relatively "simple", but I'll think more about this possibility too.

**Comment by jjegg** [comment]
Hi, I attempted to edit the rule but no changes occurred when running the new scan. Do you need to specify an argument within the rule and pass this option within the ruleset.json? Or, could you maybe provide the complete rule here so I can try this? I really believe that others would find this use case useful when it comes to remediating critical findings.

**Comment by l01cd3v** [comment]
I pushed some code on branch `issue209` to provide a proof of concept - I think I like how this works as it does not require to modify the rules, but rather allows to add conditions in the ruleset and create multiple versions of each rule.

If this works for you, then you'd just have to change all of the ec2-security-group-rules that you care for in the detailed.json ruleset, using the example below. If you happen to do so, I'd gladly accept a PR :) 

```
diff AWSScout2/rules/data/rulesets/default.json  AWSScout2/rules/data/rulesets/detailed.json 
187c187,200
<                 "level": "danger"
---
>                 "versions": {
>                     "in_use": {
>                         "conditions": [
>                             [ "_INCLUDE_(conditions/ec2-security-group-in-use.json)", "", "" ]
>                         ],
>                         "level": "danger"
>                     },
>                     "not_used": {
>                         "conditions": [
>                             [ "_INCLUDE_(conditions/ec2-security-group-not-used.json)", "", "" ]
>                         ],
>                         "level": "warning"
>                     }
>                 }
```
