### ISSUE TITLE
Combination of GovCloud and profiles seems broken

### ISSUE THREAD

**Issue by pittjl** [nccgroup/Scout2#211]
AWS CLI works in all cases. Brand new Linux VM, Scout2 3.1.0 installed from pip 10 minutes ago. Same issue seems to occur on my mac. 

Case 1 - Keys to a gov cloud account, set as default. scout2 works fine (no --profile specified)
Case 2 - Keys to a public account, specified as a profile, scout2 works fine.
Case 3 - Same keys to same gov cloud account as Case 1, specified as a profile, scout2 fails. 

Scout2 --profile govprofile --region us-gov-west-1
Traceback (most recent call last):
  File "/home/jlp/.virtualenvs/scout2/bin/Scout2", line 11, in <module>
    sys.exit(main())
  File "/home/jlp/.virtualenvs/scout2/lib/python2.7/site-packages/AWSScout2/__main__.py", line 67, in main
    aws_config.fetch(credentials, regions=args.regions, partition_name = get_partition_name(credentials))
  File "/home/jlp/.virtualenvs/scout2/lib/python2.7/site-packages/opinel/utils/aws.py", line 103, in get_partition_name
    caller_identity = get_caller_identity(credentials)
  File "/home/jlp/.virtualenvs/scout2/lib/python2.7/site-packages/opinel/utils/aws.py", line 89, in get_caller_identity
    return api_client.get_caller_identity()
  File "/home/jlp/.virtualenvs/scout2/lib/python2.7/site-packages/botocore/client.py", line 312, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/jlp/.virtualenvs/scout2/lib/python2.7/site-packages/botocore/client.py", line 605, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (InvalidClientTokenId) when calling the GetCallerIdentity operation: The security token included in the request is invalid.

**Comment by l01cd3v** [comment]
Weird, I’ll try to repro. Thanks

**Comment by l01cd3v** [comment]
Do you happen to have the default region specified in either the credentials or config file? I dont’t have access to a gov account but I’m thinking this may be why.

**Comment by pittjl** [comment]
I don't remember, since I changed the default region to us-gov-west-1 to get it to work. I've removed the default profile and specified my gov profile, and it does still fail in this way.

**Comment by l01cd3v** [comment]
I can't figure out what's wrong exactly... I know it's a weird ask but if you happen to have a dev/test govcloud account, would you mind temporarily creating a _very_ limited IAM user so that I can try to repro/fix the issue?

The error appears to happen when calling sts get-caller-identity, which is an API that is always authorized regardless of other privileges (the only "always allowed" API that I am aware of). So troubleshooting should be doable with a user who as a deny all policy like the following attached.

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Deny",
            "Action": "*",
            "Resource": "*"
        }
    ]
}
```

I usually don't like to request/get access to third party accounts, but I can't figure out a different way to access a govcloud account and feel like the perms granted are reasonable. If this is something you can do, I can be reached at loic[dot]simon[at]nccgroup[dot]trust, and my PGP key is published at https://pgp.mit.edu/pks/lookup?op=get&search=0x1A9A639A8DB9603E

**Comment by j4v** [comment]
Closing this as can't address the issue.
