### ISSUE TITLE
RDS( reference RDS #214)

### ISSUE THREAD

**Issue by bhai840** [nccgroup/Scout2#215]
subnet group is fixed.
security group still shows vpc id
parameter group displays
lot of other information

**Comment by l01cd3v** [comment]
- I'm not sure what you mean by security group still shows VPC ID - Do you have a screenshot or more details ?
- Parameter group displays the parameters - it's using the default view (which displays all the attributes). Are you seeing something different?

**Comment by bhai840** [comment]
1. Security  group displays VPC id instead of, to which security group it is attached to. It should be similar to what ec2 security  group displays

a. Example: RDS security group display
default
vpc-7caa811a
us-east-2

b. Example: EC2 security group display
Information
Description: launch-wizard-1 created 2017-10-10T14:14:14.444-05:00
Region: us-east-1
VPC: vpc-eb907692 (vpc-eb907692)
ID: sg-4303fa31
Egress Rules 1
ALL
Ports:
N/A
IP addresses:
0.0.0.0/0
Ingress Rules 1
ALL
Ports:
N/A
IP addresses:
0.0.0.0/0
Usage
EC2 Instances:
Running


When I click on parameter group below is what I see

default.mysql5.6
Attributes
DBParameterGroupFamily: mysql5.6
Description: Default parameter group for mysql5.6
arn: arn:aws:rds:us-east-1:725840360046:pg:default.mysql5.6
name: default.mysql5.6
parameters:
allow-suspicious-udfs:
source: engine-default
value:
auto_increment_increment:
source: engine-default
value:
auto_increment_offset:
source: engine-default
value:
autocommit:
source: engine-default
value:
automatic_sp_privileges:
source: engine-default
value:
back_log:
source: engine-default
value:
basedir:
source: system
value: /rdsdbbin/mysql
binlog_cache_size:
source: system
value: 32768
binlog_checksum:
source: engine-default
value:
binlog_error_action:
source: engine-default
value:
binlog_format:
source: system
value: MIXED
binlog_max_flush_queue_time:
source: engine-default
value:
binlog_order_commits:
source: engine-default
value:
tmpdir:
source: system
value: /rdsdbdata/tmp
transaction_alloc_block_size:
source: engine-default
value:
transaction_prealloc_size:
source: engine-default
value:
tx_isolation:
source: engine-default
value:
updatable_views_with_limit:
source: engine-default
value:
validate-password:
source: engine-default
value:
validate_password_dictionary_file:
source: engine-default
value:
validate_password_length:
source: engine-default
value:
validate_password_mixed_case_count:
source: engine-default
value:
validate_password_number_count:
source: engine-default
value:

**Comment by l01cd3v** [comment]
I just created a partial for the RDS parameter groups .

I believe that you may not have RDS security groups and your RDS instances are associated with VPC security groups, in which case it's normal you won't see anything. I modified how RDS security groups are fetched / stored so that VPC IDs aren't displayed anymore. If you click on RDS > security groups and see an empty list, it means all your RDS instances are in a VPC. This view is for accounts that are still "EC2 classic" enabled, in which case RDS security groups are applied to RDS instances.

**Comment by l01cd3v** [comment]
This should be fixed now - please confirm ?

**Comment by bhai840** [comment]
Hi 
Do you think  parameter group details are needed?. Please find the screen shots attached.

Also RDS instances are attached to security group. I have attached a snapshot RDS instance . Can we get security group details in the security group window?

Parameter Group Scout2
![parameter-group](https://user-images.githubusercontent.com/26830437/33037329-cf28514a-cdf6-11e7-867b-eb7b953a8e56.png)

Parameter Group  AWS
![image](https://user-images.githubusercontent.com/26830437/33037461-3cb2a5ee-cdf7-11e7-9078-fbdf919b6402.png)


Security Group details from RDS instance
![rds-security-group](https://user-images.githubusercontent.com/26830437/33037517-704905e2-cdf7-11e7-8cd0-4e2a853a395d.png)

**Comment by l01cd3v** [comment]
Yes, the parameter values are needed for the parameter groups. I may make it an accordion to get a lighter view, but some parameters are security-relevant so it makes sense to display the PG parameter values; I only display parameters that are modifiable.

According to the screenshot above, your RDS instance is in a VPC. This means that you are not in the "EC2 classic" world, and that RDS security groups do not apply (as said in my previous comment). The security groups attached to this instance are "VPC security groups". In the AWS console, you'd see their details under the "EC2 / network & security" menu, or "VPC / security / security groups". 

For now, in Scout, you are able to view the details of these security groups in the EC2 > Security group view. In the future, I may move VPC security groups under the Networking > VPC view, but this requires a fair amount of work due to a number of Scout2 internals. I can't commit such changes easily due to the risk of introducing bugs, this will require heavy testing before being rolled out.
